import { combineReducers } from '@reduxjs/toolkit';
import authReducer from './slices/authSlice.js';
import formEditorReducer from './slices/formEditorSlice.js';

// 1. Combine all your individual slices here
const appReducer = combineReducers({
  auth: authReducer,
  formEditor: formEditorReducer,
});

// 2. Wrap it in a Root Reducer to intercept global actions
const rootReducer = (state, action) => {
  // If the user logs out, we intercept the action and destroy the entire state tree!
  // 'auth/logoutSuccess' is the exact action name generated by our authSlice
  if (action.type === 'auth/logoutSuccess') {
    // Setting state to undefined forces all reducers to revert to their initialState
    state = undefined; 
  }

  return appReducer(state, action);
};

export default rootReducer;